# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b4a70f5800b80d7a3083fc548ba8c236c7b9e759e3c49918c365de8d2effe63d1d266d951a9cba0fa65b0fa993e20e284a4e9d7f90862e14469175563bb8f0

test:
  secret_key_base: 9003ba98252680d3bc56c5f5f0ace15bba6beeea3507afe335af0ad9319ee31617a7cb4a379aa6ac4f682d61370e04687d38275a00646ac03d70f234acddfe98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
